#!/usr/bin/env python3
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import sys
import time

try:
    # Check to make sure a url has been specified
    if len(sys.argv) < 2:
        print("Error: a url to save must be specified")
        print("Usage: wayback URL [URL...] ")
        sys.exit(1)
    
    # Initialize driver
    wd = webdriver.Firefox()
    # Create wait object with a timeout of 60 seconds
    wait = WebDriverWait(wd, 60)

    # Loop through each url provided
    for url in sys.argv[1:]:
        # Print progress message
        print("\rOpening url:", url,)

        # Make a get request to archive.org's save snapshot page
        wd.get("https://web.archive.org/save/" + url)

        # Wait until save saving is complete
        wait.until(EC.visibility_of_element_located((By.ID, "wm-logo")))
        wait.until(lambda _: wd.execute_script("return document.readyState == 'complete'"))
finally:
    wd.quit()
